/*
 * DSS - Digital Signature Services
 *
 * Copyright (C) 2011 European Commission, Directorate-General Internal Market and Services (DG MARKT), B-1049 Bruxelles/Brussel
 *
 * Developed by: 2011 ARHS Developments S.A. (rue Nicolas Bové 2B, L-1253 Luxembourg) http://www.arhs-developments.com
 *
 * This file is part of the "DSS - Digital Signature Services" project.
 *
 * "DSS - Digital Signature Services" is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * DSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * "DSS - Digital Signature Services".  If not, see <http://www.gnu.org/licenses/>.
 */

package eu.europa.ec.markt.tlmanager.view.pages;

import eu.europa.ec.markt.tlmanager.core.Configuration;
import eu.europa.ec.markt.tlmanager.core.QNames;
import eu.europa.ec.markt.tlmanager.model.treeNodes.TSLDataNode;
import eu.europa.ec.markt.tlmanager.view.binding.BindingManager;
import eu.europa.ec.markt.tlmanager.view.binding.ElectronicAddressConverter;
import eu.europa.ec.markt.tlmanager.view.binding.InternationalNamesConverter;
import eu.europa.ec.markt.tlmanager.view.binding.NonEmptyMultiLangURIListConverter;
import eu.europa.ec.markt.tlmanager.view.binding.PostalAddressListConverter;
import eu.europa.ec.markt.tlmanager.view.binding.TSPInformationExtensionConverter;
import eu.europa.ec.markt.tlmanager.view.multivalue.MultiMode;
import eu.europa.ec.markt.tsl.jaxb.tsl.TSPInformationType;
import eu.europa.ec.markt.tsl.jaxb.tsl.TSPType;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JTree;

/**
 * Content page for managing all below a <tsl:TSPInformation/>.
 * 
 *
 * @version $Revision: 2840 $ - $Date: 2013-11-04 12:30:49 +0100 (lun., 04 nov. 2013) $
 */

public class TSPInformationPage extends TreeDataPublisher {

    private static final Logger LOG = Logger.getLogger(TSPInformationPage.class.getName());

    /**
     * Instantiates a new tSP information page.
     */
    public TSPInformationPage(JTree jtree) {
        super(jtree);
        initComponents();
        tspTitle.setTitle(uiKeys.getString("TSPInformationPage.tspTitle.title"));
        initBinding();

        additionalSetup();
    }

    /** {@inheritDoc} */
    @Override
    public void setName() {
        setName(TreeDataPublisher.TSP_INFORMATION_PAGE);
    }

    /** {@inheritDoc} */
    @Override
    protected void setupMandatoryLabels() {
        setMandatoryLabel(tspNameLabel);
        setMandatoryLabel(postalAddressLabel);
        setMandatoryLabel(electronicAddressLabel);
        setMandatoryLabel(informationURILabel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tspTitle = new eu.europa.ec.markt.tlmanager.view.common.TitledPanel();
        tspNameLabel = new javax.swing.JLabel();
        tspName = new eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton(MultiMode.MULTILANG_TEXT, Configuration.LanguageCodes.getEnglishLanguage(), null);
        tradeName = new eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton(MultiMode.MULTILANG_TEXT, Configuration.LanguageCodes.getEnglishLanguage(), null);
        postalAddress = new eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton(MultiMode.MULTILANG_POSTAL, Configuration.LanguageCodes.getEnglishLanguage(), null);
        electronicAddress = new eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton(MultiMode.MULTI_MULTILANGANYURI, null, null);
        informationURI = new eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton(MultiMode.MULTILANG_TEXT, Configuration.LanguageCodes.getEnglishLanguage(), null);
        informationExtension = new eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton(MultiMode.MULTI_TSPINEX, null, null);
        tspTradeNameLabel = new javax.swing.JLabel();
        postalAddressLabel = new javax.swing.JLabel();
        electronicAddressLabel = new javax.swing.JLabel();
        informationURILabel = new javax.swing.JLabel();
        informationExtensionLabel = new javax.swing.JLabel();

        tspNameLabel.setLabelFor(tspName);
        tspNameLabel.setText(uiKeys.getString("TSPInformationPage.tspNameLabel.text")); // NOI18N

        tspTradeNameLabel.setLabelFor(tradeName);
        tspTradeNameLabel.setText(uiKeys.getString("TSPInformationPage.tspTradeNameLabel.text")); // NOI18N

        postalAddressLabel.setLabelFor(postalAddress);
        postalAddressLabel.setText(uiKeys.getString("TSPInformationPage.postalAddressLabel.text")); // NOI18N

        electronicAddressLabel.setLabelFor(electronicAddress);
        electronicAddressLabel.setText(uiKeys.getString("TSPInformationPage.electronicAddressLabel.text")); // NOI18N

        informationURILabel.setLabelFor(informationURI);
        informationURILabel.setText(uiKeys.getString("TSPInformationPage.informationURILabel.text")); // NOI18N

        informationExtensionLabel.setLabelFor(informationExtension);
        informationExtensionLabel.setText(uiKeys.getString("TSPInformationPage.informationExtensionLabel.text")); // NOI18N

        javax.swing.GroupLayout tspTitleLayout = new javax.swing.GroupLayout(tspTitle);
        tspTitle.setLayout(tspTitleLayout);
        tspTitleLayout.setHorizontalGroup(
            tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tspTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationExtensionLabel)
                    .addComponent(postalAddressLabel)
                    .addComponent(tspTradeNameLabel)
                    .addComponent(tspNameLabel)
                    .addComponent(electronicAddressLabel)
                    .addComponent(informationURILabel))
                .addGap(36, 36, 36)
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tradeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postalAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(electronicAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informationURI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informationExtension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tspName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tspTitleLayout.setVerticalGroup(
            tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tspTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tspName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tspNameLabel))
                .addGap(18, 18, 18)
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tspTradeNameLabel)
                    .addComponent(tradeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postalAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electronicAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(electronicAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationURILabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(informationURI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tspTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationExtension, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(informationExtensionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tspTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tspTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton electronicAddress;
    private javax.swing.JLabel electronicAddressLabel;
    private eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton informationExtension;
    private javax.swing.JLabel informationExtensionLabel;
    private eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton informationURI;
    private javax.swing.JLabel informationURILabel;
    private eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton postalAddress;
    private javax.swing.JLabel postalAddressLabel;
    private eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton tradeName;
    private eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton tspName;
    private javax.swing.JLabel tspNameLabel;
    private eu.europa.ec.markt.tlmanager.view.common.TitledPanel tspTitle;
    private javax.swing.JLabel tspTradeNameLabel;
    // End of variables declaration//GEN-END:variables
    /*
     * (non-Javadoc)
     * 
     * @see javax.swing.event.TreeSelectionListener#valueChanged(javax.swing.event.TreeSelectionEvent)
     */

    private void initBinding() {
        if (bindingManager == null) {
            bindingManager = new BindingManager(this);
        }

        bindingManager.createBindingForComponent(tspName.getMultivaluePanel(), "TSPName", QNames._TSPName);
        bindingManager.appendConverter(new InternationalNamesConverter(), QNames._TSPName);

        bindingManager.createBindingForComponent(tradeName.getMultivaluePanel(), "TSPTradeName",
                QNames._TSPTradeName);
        bindingManager.appendConverter(new InternationalNamesConverter(), QNames._TSPTradeName);

        bindingManager.createBindingForComponent(postalAddress.getMultivaluePanel(), "postalAddresses",
                QNames._PostalAddress_QNAME.getLocalPart());
        bindingManager.appendConverter(new PostalAddressListConverter(), QNames._PostalAddress_QNAME.getLocalPart());

        bindingManager.createBindingForComponent(electronicAddress.getMultivaluePanel(), "electronicAddress",
                QNames._ElectronicAddress_QNAME.getLocalPart());
        bindingManager.appendConverter(new ElectronicAddressConverter(),
                QNames._ElectronicAddress_QNAME.getLocalPart());

        bindingManager.createBindingForComponent(informationURI.getMultivaluePanel(), "TSPInformationURI",
                QNames._TSPInformation_QNAME.getLocalPart());
        bindingManager.appendConverter(new NonEmptyMultiLangURIListConverter(),
                QNames._TSPInformation_QNAME.getLocalPart());

        bindingManager.createBindingForComponent(informationExtension.getMultivaluePanel(),
                "TSPInformationExtensions", QNames._Extension_QNAME.getLocalPart());
        bindingManager.appendConverter(new TSPInformationExtensionConverter(),
                QNames._Extension_QNAME.getLocalPart());
    }

    /** {@inheritDoc} */
    @Override
    public void updateViewFromData(TSLDataNode dataNode) {
        this.dataNode = dataNode;
        TSPType tsp = (TSPType) dataNode.getUserObject();
        TSPInformationType tspInformation = tsp.getTSPInformation();
        LOG.log(Level.FINE, "Value changed {0}", tsp);

        bindingManager.unbindAll();

        bindingManager.amendSourceForBinding(tspInformation, QNames._TSPName);
        bindingManager.amendSourceForBinding(tspInformation, QNames._TSPTradeName);

        bindingManager.amendSourceForBinding(tspInformation.getTSPAddress(),
                QNames._PostalAddress_QNAME.getLocalPart());
        bindingManager.amendSourceForBinding(tspInformation.getTSPAddress(),
                QNames._ElectronicAddress_QNAME.getLocalPart());

        bindingManager.amendSourceForBinding(tspInformation, QNames._TSPInformation_QNAME.getLocalPart());

        bindingManager.amendSourceForBinding(tspInformation, QNames._Extension_QNAME.getLocalPart());

        bindingManager.bindAll();

        // update all the preview information on the multivalue buttons
        electronicAddress.refreshContentInformation();
        informationExtension.refreshContentInformation();
        informationURI.refreshContentInformation();
        postalAddress.refreshContentInformation();
        tradeName.refreshContentInformation();
        tradeName.refreshContentInformation();
        tspName.refreshContentInformation();
    }
}